preprocessing:
  storage_format: parquet
  compression: snappy
  save_transformed_data: true

  feat_stage:
    enabled: true
    transformers:
      - type: StandardScalerTransformer
        columns:
          - annual_income
          - debt_to_income_ratio
          - credit_score
          - loan_amount
          - interest_rate

  cv_stage:
    enabled: true
    transformers:
      - type: TargetEncodingTransformer
        columns:
          - gender
          - marital_status
          - education_level
          - employment_status
          - loan_purpose
          - grade_subgrade
        target: loan_paid_back
        smoothing: 10.0
        min_samples_leaf: 5
