import pandas as pd                                                                                                                                                                                                                                                                                 
from xgboost import XGBClassifier                                                                                                                                                                                                                                                                   
from sklearn.model_selection import train_test_split, cross_val_score                                                                                                                                                                                                                               
from sklearn.metrics import accuracy_score                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                      
# Load data                                                                                                                                                                                                                                                                                         
train = pd.read_csv('./input/train.csv')                                                                                                                                                                                                                                                            
test = pd.read_csv('./input/test.csv')                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                      
# Preprocessing                                                                                                                                                                                                                                                                                     
X = train.drop(columns=['Depression', 'id'])                                                                                                                                                                                                                                                        
y = train['Depression']                                                                                                                                                                                                                                                                             
idd
X.fillna(X.mode().iloc[0], inplace=True)                                                                                                                                                                                                                                                            
X.fillna(X.mean(), inplace=True)                                                                                                                                                                                                                                                                    
# Identify categorical features                                                                                                                                                                                                                                                                     
cat_features = X.select_dtypes(include=["object"]).columns.tolist()                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                      
# Train XGBClassifier                                                                                                                                                                                                                                                                               
model = XGBClassifier(use_label_encoder=False, eval_metric='logloss')                                                                                                                                                                                                                               
scores = cross_val_score(model, X, y, cv=5, scoring='accuracy')                                                                                                                                                                                                                                     
accuracy = scores.mean()                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                      
# Fit model and make predictions                                                                                                                                                                                                                                                                    
model.fit(X, y)                                                                                                                                                                                                                                                                                     
test.fillna(test.mode().iloc[0], inplace=True)                                                                                                                                                                                                                                                      
test.fillna(test.mean(), inplace=True)                                                                                                                                                                                                                                                              
predictions = model.predict(test.drop(columns=['id']))                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                      
# Save predictions                                                                                                                                                                                                                                                                                  
submission = pd.DataFrame({'id': test['id'], 'Depression': predictions})                                                                                                                                                                                                                            
submission.to_csv('./working/submission.csv', index=False)                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                      
# Print evaluation metric                                                                                                                                                                                                                                                                           
print("Cross-validated accuracy:", accuracy)                           
