templates:
  fast-cpu:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: medium_quality
        time_limit: 60
        use_gpu: false
        excluded_models:
          - NN_TORCH
  dev-cpu:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: medium_quality
        time_limit: 300
        use_gpu: false
  dev-gpu:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: medium_quality
        time_limit: 300
        use_gpu: true
  best-cpu:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 3600
        use_gpu: false
  best-gpu:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 3600
        use_gpu: true
  extreme-gpu:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: extreme_quality
        time_limit: 86400
        use_gpu: true
  time8-cpu:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: false

  nn-8h-gpu:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: true
        included_model_types: ["NN_TORCH"]

  gbm-8h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: false
        included_model_types: ["GBM"]

  cat-8h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: false
        included_model_types: ["CAT"]

  xgb-8h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: false
        included_model_types: ["XGB"]

  fastai-8h-gpu:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: true
        included_model_types: ["FASTAI"]

  rf-8h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: false
        included_model_types: ["RF"]

  xt-8h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: false
        included_model_types: ["XT"]

  cpu-boost-8h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: false
        excluded_models:
          - NN_TORCH
          - FASTAI

  gbm-cat-xgb-8h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: false
        included_model_types: ["GBM", "CAT", "XGB"]
