templates:
  cpu-fast-1m:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: medium_quality
        time_limit: 60
        use_gpu: false
        excluded_models:
          - NN_TORCH
  cpu-dev-5m:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: medium_quality
        time_limit: 300
        use_gpu: false
  gpu-dev-5m:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: medium_quality
        time_limit: 300
        use_gpu: true
  cpu-best-1h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 3600
        use_gpu: false
  gpu-best-1h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 3600
        use_gpu: true
  gpu-extreme-24h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: extreme_quality
        time_limit: 86400
        use_gpu: true
  cpu-best-8h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: false

  gpu-torch-8h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: true
        included_model_types: ["NN_TORCH"]

  cpu-gbm-8h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: false
        included_model_types: ["GBM"]

  cpu-cat-8h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: false
        included_model_types: ["CAT"]

  cpu-xgb-8h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: false
        included_model_types: ["XGB"]

  gpu-fastai-8h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: true
        included_model_types: ["FASTAI"]

  cpu-rf-8h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: false
        included_model_types: ["RF"]

  cpu-xt-8h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: false
        included_model_types: ["XT"]

  cpu-knn-8h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: false
        included_model_types: ["KNN"]

  cpu-ebm-8h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: false
        included_model_types: ["EBM"]

  cpu-nonn-8h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: false
        included_model_types: ["GBM", "CAT", "XGB", "RF", "XT", "KNN", "LR"]

  cpu-boost-8h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: false
        included_model_types: ["GBM", "CAT", "XGB"]

  gpu-boost-8h:
    model: autogluon_baseline
    config:
      hyperparameters:
        presets: best_quality
        time_limit: 28800
        use_gpu: true
        included_model_types: ["GBM", "CAT", "XGB"]
