"""Prediction module."""

from __future__ import annotations

from pathlib import Path
from typing import Optional

# pandas imported in execute()


from mlarena.core.module import BaseModule, ModuleResult
from mlarena.core.registry import ModuleRegistry
from mlarena.utils.project import data_paths, load_project_config, load_submission_module


def _load_predictor(model_artifact: Path):
    from autogluon.tabular import TabularPredictor

    return TabularPredictor.load(str(model_artifact))


@ModuleRegistry.register
class PredictModule(BaseModule):
    name = "predict"
    description = "Generate predictions"
    dependencies = {"model"}

    @classmethod
    def register_cli_args(cls, parser) -> None:
        parser.add_argument("--predict-suffix", type=str, default="", help="Optional suffix for submission filename.")

    def execute(self) -> ModuleResult:
        import pandas as pd
        artifact_dir: Path = self.context.artifact_dir
        artifact_dir.mkdir(parents=True, exist_ok=True)
        config = self.context.config_module or load_project_config(self.context.project_root)
        submission_helper = load_submission_module(self.context.project_root)

        model_entry = self.context.state.modules.get("model")
        if not model_entry or not getattr(model_entry, "payload", None):
            marker = artifact_dir / "predict_failed.txt"
            marker.write_text("Model step missing payload.")
            return ModuleResult(success=False, error="model not run", artifacts=[marker])

        model_artifact = Path(model_entry.payload["model_artifact"])  # type: ignore
        predictor = _load_predictor(model_artifact)

        pre_entry = self.context.state.modules.get("preprocess")
        processed = getattr(pre_entry, "payload", {}) if pre_entry else {}
        test_path: Optional[Path] = None
        if processed and processed.get("test_processed"):
            test_path = Path(processed["test_processed"])
        if test_path is None or not test_path.exists():
            _, test_path = data_paths(config)

        test_df = pd.read_csv(test_path)
        id_col = getattr(config, "ID_COLUMN", None)
        id_series = test_df[id_col] if id_col and id_col in test_df.columns else None
        if id_col and id_col in test_df.columns:
            test_df = test_df.drop(columns=[id_col])

        submit_probas = bool(getattr(config, "SUBMISSION_PROBAS", False))
        if submit_probas and predictor.problem_type != "regression":
            preds = predictor.predict_proba(test_df, as_multiclass=False)
        else:
            preds = predictor.predict(test_df)

        submission_df = pd.DataFrame()
        if id_series is not None:
            submission_df[id_col] = id_series
        else:
            submission_df["id"] = range(len(preds))
        submission_df[getattr(config, "TARGET_COLUMN", "target")] = preds

        # Generate filename with timestamp (like old code)
        from datetime import datetime
        suffix = self.invocation_params.get("predict_suffix")
        if suffix:
            fname = f"submission-{suffix}.csv"
        else:
            timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
            fname = f"submission-{timestamp}.csv"
        submission_path = artifact_dir / fname
        submission_df.to_csv(submission_path, index=False)

        # Create submission entry via helper (tracks experiment if available)
        try:
            submission_helper.create_submission(
                preds,
                id_series if id_series is not None else submission_df.iloc[:, 0],
                model_name="mlarena",
                local_cv_score=None,
                notes="Generated by MLArena",
                filename_prefix=submission_path.stem,
                track=False,
            )
        except Exception:
            # Best-effort; creation is optional here.
            pass

        return ModuleResult(
            success=True,
            payload={
                "predictions": str(submission_path),
                "submission_file": str(submission_path),
            },
            artifacts=[submission_path],
        )
