templates:
  cpu-fast-1m:
    model: autogluon_baseline
    config:
      preset: medium
      time_limit: 60
      use_gpu: false
      excluded_model_types:
        - NN_TORCH
        - FASTAI

  cpu-dev-5m:
    model: autogluon_baseline
    config:
      preset: medium
      time_limit: 300
      use_gpu: false

  gpu-dev-5m:
    model: autogluon_baseline
    config:
      preset: medium
      time_limit: 300
      use_gpu: true

  cpu-best-1h:
    model: autogluon_baseline
    config:
      preset: best
      time_limit: 3600
      use_gpu: false

  gpu-best-1h:
    model: autogluon_baseline
    config:
      preset: best
      time_limit: 3600
      use_gpu: true

  gpu-extreme-24h:
    model: autogluon_baseline
    config:
      preset: extreme
      time_limit: 86400
      use_gpu: true

  cpu-best-8h:
    model: autogluon_baseline
    config:
      preset: best
      time_limit: 28800
      use_gpu: false

  gpu-torch-8h:
    model: autogluon_baseline
    config:
      preset: best
      time_limit: 28800
      use_gpu: true
      included_model_types: ["NN_TORCH"]
      hyperparameters:
        NN_TORCH:
          - ag_args_fit:
              num_gpus: 1
              num_workers: 0
              batch_size: 256

  cpu-gbm-8h:
    model: autogluon_baseline
    config:
      preset: best
      time_limit: 28800
      use_gpu: false
      included_model_types: ["GBM"]

  cpu-cat-8h:
    model: autogluon_baseline
    config:
      preset: best
      time_limit: 28800
      use_gpu: false
      included_model_types: ["CAT"]

  cpu-xgb-8h:
    model: autogluon_baseline
    config:
      preset: best
      time_limit: 28800
      use_gpu: false
      included_model_types: ["XGB"]

  gpu-fastai-8h:
    model: autogluon_baseline
    config:
      preset: best
      time_limit: 28800
      use_gpu: true
      included_model_types: ["FASTAI"]
      hyperparameters:
        FASTAI:
          - ag_args_fit:
              num_gpus: 1
              num_workers: 0
              batch_size: 256

  cpu-rf-8h:
    model: autogluon_baseline
    config:
      preset: best
      time_limit: 28800
      use_gpu: false
      included_model_types: ["RF"]

  cpu-xt-8h:
    model: autogluon_baseline
    config:
      preset: best
      time_limit: 28800
      use_gpu: false
      included_model_types: ["XT"]

  cpu-knn-8h:
    model: autogluon_baseline
    config:
      preset: best
      time_limit: 28800
      use_gpu: false
      included_model_types: ["KNN"]

  cpu-ebm-8h:
    model: autogluon_baseline
    config:
      preset: best
      time_limit: 28800
      use_gpu: false
      included_model_types: ["EBM"]

  cpu-nonn-8h:
    model: autogluon_baseline
    config:
      preset: best
      time_limit: 28800
      use_gpu: false
      included_model_types: ["GBM", "CAT", "XGB", "RF", "XT", "KNN", "LR"]

  cpu-boost-8h:
    model: autogluon_baseline
    config:
      preset: best
      time_limit: 28800
      use_gpu: false
      included_model_types: ["GBM", "CAT", "XGB"]

  gpu-boost-8h:
    model: autogluon_baseline
    config:
      preset: best
      time_limit: 28800
      use_gpu: true
      included_model_types: ["GBM", "CAT", "XGB"]
      hyperparameters:
        ag_args_fit:
          num_gpus: 1
          num_cpus: 8
        GBM:
          - device: gpu
        CAT:
          - task_type: GPU
            devices: "0"
        XGB:
          - device: cuda
            tree_method: hist
            n_jobs: 8
